version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    command: npm run dev -- --host
    environment:
      - VITE_APP_SUBDOMAIN=elvan  # Custom environment variable
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
